version: '3.3'
services:
  node:
    build:
      context: ./app/api
      dockerfile: dockerfile.dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
  vue:
    build:
      context: ./app/web
      dockerfile: dockerfile.dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8881:8881"
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
networks:
  default:
    external: true
    name: tuxtum